services:
  pocketbase:
    image: ${IMAGE_NAME}:${VERSION}
    build:
      context: .
      args:
        TARGETOS: linux
        TARGETARCH: ${TARGETARCH:-amd64}
        PB_VERSION: 0.28.4
        PB_ENV: production
    container_name: indyhackers
    environment:
      NODE_ENV: production
    volumes:
      - ./pb/data:/pb_data
      # - ./pb/public:/pb_public
      - ./pb/hooks:/pb_hooks
