services:
  indyhackers-redux:
    image: indyhackers-${TARGETARCH:-amd64}:${VERSION}
    build:
      context: .
      args:
        TARGETOS: linux
        TARGETARCH: ${TARGETARCH:-amd64}
        PB_VERSION: 0.28.4
        PB_ENV: development
    container_name: pocketbase
    environment:
      NODE_ENV: development
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./pb/data:/pb_data
      # - ./pb/public:/pb_public
      - ./dist:/pb_public
      - ./pb/hooks:/pb_hooks
      - ./pb/migrations:/pb_migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
