name: cd

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true

env:
  SSH_HOST: indyhackersdev.highcapacity.net

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_DEV }}

      - name: Deploy image on host
        run: |
          ssh-keyscan ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts
          
          #stop running containers
          ssh ${{ env.SSH_HOST }} docker stop `docker ps -a -q`
          ssh ${{ env.SSH_HOST }} docker rm `docker ps -a -q`
          
          #run new image
          ssh ${{ env.SSH_HOST }} docker run --restart always -p 32768:80 -d ${{ inputs.image }}
