name: cd

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      ssh_host:
        type: string
        required: true
      ssh_user:
        type: string
        required: true
    secrets:
      ts_oauth_client_id:
        required: true
      ts_oauth_secret:
        required: true
      ssh_key:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.ts_oauth_client_id }}
          oauth-secret: ${{ secrets.ts_oauth_secret }}
          tags: tag:ci

      - name: SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ssh_key }}

      - name: Deploy image on host
        run: |
          #stop running containers
          ssh -o StrictHostKeyChecking=accept-new ${{ inputs.SSH_USER }}@${{ inputs.SSH_HOST }} docker stop indyhackers || true
          ssh -o StrictHostKeyChecking=accept-new ${{ inputs.SSH_USER }}@${{ inputs.SSH_HOST }} docker rm indyhackers || true
          
          #run new image
          ssh -o StrictHostKeyChecking=accept-new ${{ inputs.SSH_USER }}@${{ inputs.SSH_HOST }} docker run --name indyhackers -e NODE_ENV=production --restart always -p 32768:8090 -v ./pb/data:/pb_data -v ./pb/hooks:/pb_hooks -d ${{ inputs.image }}

          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"New image deployed to indyhackers.org: `${{ inputs.image }}`"}' \
            https://hooks.slack.com/services/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