name: CI

on: push

env:
  IMAGE_NAME: apoland/indyhackers

jobs:
  build:
    runs-on: self-hosted
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: apoland
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push image to Dockerhub
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          VERSION: ${{ github.sha }}
        run: |
          docker compose -f docker-compose.yaml -f docker-compose_production.yaml build
          docker push $IMAGE_NAME:$VERSION
          echo "image=$IMAGE_NAME:$VERSION" >> $GITHUB_OUTPUT

  cd:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    uses: ./.github/workflows/cd.yaml
    with:
      image: ${{ needs.build.outputs.image }}
      ssh_user: indyhackers
      ssh_host: indyhackersdev.highcapacity.net
    secrets:
      ssh_key: ${{ secrets.SSH_KEY_DEV }}
